data = [
    {"name": "Cristiano Ronaldo", "followers": 620000000, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "followers": 500000000, "description": "Footballer", "country": "Argentina"},
    {"name": "Virat Kohli", "followers": 270000000, "description": "Cricketer", "country": "India"},
    {"name": "Neymar Jr", "followers": 220000000, "description": "Footballer", "country": "Brazil"},
    {"name": "LeBron James", "followers": 160000000, "description": "Basketball Player", "country": "USA"},
    {"name": "Rohit Sharma", "followers": 40000000, "description": "Cricketer", "country": "India"},
    {"name": "MS Dhoni", "followers": 45000000, "description": "Cricketer", "country": "India"},
    {"name": "Kylian Mbappe", "followers": 120000000, "description": "Footballer", "country": "France"},
    {"name": "Erling Haaland", "followers": 40000000, "description": "Footballer", "country": "Norway"},
    {"name": "Novak Djokovic", "followers": 15000000, "description": "Tennis Player", "country": "Serbia"},
    {"name": "Roger Federer", "followers": 12000000, "description": "Tennis Player", "country": "Switzerland"},
    {"name": "Rafael Nadal", "followers": 18000000, "description": "Tennis Player", "country": "Spain"},
    {"name": "Serena Williams", "followers": 17000000, "description": "Tennis Player", "country": "USA"},
    {"name": "Simone Biles", "followers": 7000000, "description": "Gymnast", "country": "USA"},
    {"name": "Usain Bolt", "followers": 13000000, "description": "Sprinter", "country": "Jamaica"},
    {"name": "Hardik Pandya", "followers": 30000000, "description": "Cricketer", "country": "India"},
    {"name": "KL Rahul", "followers": 20000000, "description": "Cricketer", "country": "India"},
    {"name": "Jasprit Bumrah", "followers": 15000000, "description": "Cricketer", "country": "India"},
    {"name": "Sania Mirza", "followers": 10000000, "description": "Tennis Player", "country": "India"},
    {"name": "PV Sindhu", "followers": 5000000, "description": "Badminton Player", "country": "India"},
    {"name": "Saina Nehwal", "followers": 6000000, "description": "Badminton Player", "country": "India"},
    {"name": "Conor McGregor", "followers": 45000000, "description": "MMA Fighter", "country": "Ireland"},
    {"name": "Khabib Nurmagomedov", "followers": 35000000, "description": "MMA Fighter", "country": "Russia"},
    {"name": "Zlatan Ibrahimovic", "followers": 60000000, "description": "Footballer", "country": "Sweden"},
    {"name": "Kevin De Bruyne", "followers": 25000000, "description": "Footballer", "country": "Belgium"},
    {"name": "Mohamed Salah", "followers": 60000000, "description": "Footballer", "country": "Egypt"},
    {"name": "David Beckham", "followers": 80000000, "description": "Footballer", "country": "England"},
    {"name": "Sergio Ramos", "followers": 60000000, "description": "Footballer", "country": "Spain"},
    {"name": "Karim Benzema", "followers": 70000000, "description": "Footballer", "country": "France"},
    {"name": "Antoine Griezmann", "followers": 40000000, "description": "Footballer", "country": "France"},
    {"name": "Luka Modric", "followers": 30000000, "description": "Footballer", "country": "Croatia"},
    {"name": "Paul Pogba", "followers": 60000000, "description": "Footballer", "country": "France"},
    {"name": "Eden Hazard", "followers": 35000000, "description": "Footballer", "country": "Belgium"},
    {"name": "Wayne Rooney", "followers": 20000000, "description": "Footballer", "country": "England"},
    {"name": "Virender Sehwag", "followers": 10000000, "description": "Cricketer", "country": "India"},
    {"name": "Yuvraj Singh", "followers": 15000000, "description": "Cricketer", "country": "India"},
    {"name": "Ravindra Jadeja", "followers": 20000000, "description": "Cricketer", "country": "India"},
    {"name": "Shikhar Dhawan", "followers": 12000000, "description": "Cricketer", "country": "India"},
    {"name": "Ben Stokes", "followers": 5000000, "description": "Cricketer", "country": "England"},
    {"name": "Joe Root", "followers": 4000000, "description": "Cricketer", "country": "England"},
    {"name": "Steve Smith", "followers": 4500000, "description": "Cricketer", "country": "Australia"},
    {"name": "David Warner", "followers": 10000000, "description": "Cricketer", "country": "Australia"},
    {"name": "Pat Cummins", "followers": 3000000, "description": "Cricketer", "country": "Australia"},
    {"name": "Mitchell Starc", "followers": 2000000, "description": "Cricketer", "country": "Australia"},
    {"name": "Kane Williamson", "followers": 3000000, "description": "Cricketer", "country": "New Zealand"},
    {"name": "Babar Azam", "followers": 5000000, "description": "Cricketer", "country": "Pakistan"},
    {"name": "Shaheen Afridi", "followers": 2000000, "description": "Cricketer", "country": "Pakistan"},
    {"name": "Andre Russell", "followers": 4000000, "description": "Cricketer", "country": "West Indies"},
    {"name": "Chris Gayle", "followers": 10000000, "description": "Cricketer", "country": "West Indies"},
    {"name": "Dwayne Bravo", "followers": 5000000, "description": "Cricketer", "country": "West Indies"},
    {"name": "Tiger Woods", "followers": 3000000, "description": "Golfer", "country": "USA"},
    {"name": "Michael Phelps", "followers": 4000000, "description": "Swimmer", "country": "USA"},
    {"name": "Lewis Hamilton", "followers": 35000000, "description": "F1 Driver", "country": "UK"},
    {"name": "Max Verstappen", "followers": 15000000, "description": "F1 Driver", "country": "Netherlands"}
]